apiVersion: v1
kind: Service
metadata:
  name: to-do-app
spec:
  type: NodePort
  selector:
    app: to-do-app
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1234
      targetPort: 8080
